name: basics-workflow-name

on:
  pull_request:
  push:
  workflow_call:

jobs:
  basics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install \
            --no-install-recommends \
            python3-pytest

      - name: run program
        run: |
            python3 hello.py

      - name: create output capture file
        run: |
            python3 hello.py > output.txt

